# Generated by Django 5.2.7 on 2025-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_found_pics/'),
        ),
    ]
